# REQUEST
std_msgs/String object_id
uint8 object_type
geometry_msgs/PoseStamped target

uint8 NO_TYPE = 0
uint8 DIAL_GAUGE = 1
uint8 HOTSPOT = 2
uint8 LEVEL_GAUGE = 4
uint8 VALVE = 8

---

# RESPONSE
uint8 success
uint8 SUCCESS = 0
uint8 SAMPLING_FAILED = 1
uint8 PLANNING_FAILED = 2
uint8 MOVE_ARM_FAILED = 3
uint8 FAILED = 255

---

# FEEDBACK
uint8 status
uint8 SUCCESS = 0
uint8 FAILED  = 255
uint8 SAMPLING = 1
uint8 PLANNING = 2
uint8 CONTROL = 4
uint8 REPLAN = 8
