# REQUEST
std_msgs/String object_id
ObjectTypes object_type
ActionCodes action_type
float64 base_yaw
geometry_msgs/PoseStamped target

---

# RESPONSE
ErrorCodes success
geometry_msgs/PoseStamped waypoint

---

# FEEDBACK
ErrorCodes status
